CREATE TABLE summaryreport
(
	id int NOT NULL AUTO_INCREMENT,
	inserted Datetime NOT NULL,
	srfstatus int(3),
	srfid varchar(25) NOT NULL,
	curdate varchar(15),
	aplname varchar(25),
	apfname varchar(25),
	crlines varchar(3),
	crgood varchar(3),
	crneg varchar(3),
	crevictions varchar(3),
	crinquires varchar(3),
	creditscore varchar(3),
	civiljudgements varchar(3),
	cjcount  varchar(3),
	cjdfmonth varchar(2),
	cjdfyear varchar(4),
	taxliens varchar(3),
	tlcount varchar(3),
	taxliens_released varchar(3),
	bankruptcy varchar(3),
	bankruptcyType varchar(3),
	bankruptcydf varchar(10),
	bankruptcy_open varchar(10),
	bankruptcy_closed varchar(10),
	telecheckType varchar(10),
	ssnstatus varchar(15),
	comments varchar(215),
	charcounter varchar(3),
	mgrAgentOwner varchar(30),
	mgrPhone varchar(20),
	propMgtCo varchar(30),
	propMgtCoFax varchar(20),
	aptComplex varchar(30),
	acctholder varchar(25),
	numOfPages varchar(3),
	UNIQUE KEY id (id)
);